[package]
name = "privnoters"
version = "0.1.0"
authors = ["Dave Allie <dave@daveallie.com>"]

[dependencies]
base64 = "0.9"
rust-crypto = "^0.2"
rand = "0.4"
hyper = "0.11"
hyper-tls = "0.1.3"
futures = "0.1"
tokio-core = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.7"
